### PR TITLE
Remove -Werror to make pip happy.

### PR DESCRIPTION
**Pull request by matz-e**

### CODE REVIEW

**Comment by mgeplf** [comment]
What was pip complaining about?

**Comment by matz-e** [comment]
@wizmer pointed out that one some systems/compilers `-Werror` may lead to a failing `pip install`, which will be hard for users to fix/debug.

**Comment by mgeplf** [comment]
Ah, interesting.  Which compilers don't support -Werror @wizmer?

**Comment by matz-e** [comment]
> Ah, interesting. Which compilers don't support -Werror @wizmer?

I don't think that certain compilers don't support `-Werror`, but rather that different compilers apply different standards - a build that may pass for us may fail for a user.

**Comment by mgeplf** [comment]
Yeah, thanks.  -Werror should only be applied in CI, and cause failures there, allowing people to install, and covering us from making mistakes

**Pull request merged**
