### PR TITLE
small shell script cleanups for wheelbuilding

### PR DESCRIPTION
**Pull request by mgeplf**
* enable python 3.5
* turn on more error handling (set -euxo pipefail)
* allow for building the docker image locally, without it trying to push it as if it were run in Jenkins
* export fewer environment variables

### CODE REVIEW

**Comment by wizmer** [comment]
Well, actually, the whole `packaging` folder can be thrown away now that we build with `multibuild`

**Comment by mgeplf** [comment]
We shouldn't leave dead code in the repo, because then I waste time cleaning it up.

Also, what/who is in charge of bluebrain/morphio_wheel docker container?

**Comment by wizmer** [comment]
Yes, sorry, I totally forgot about that. 
> Also, what/who is in charge of bluebrain/morphio_wheel docker container?
It's me, I'll put the stuff to build the container in the morphio-wheel repo instead.

**Comment by mgeplf** [comment]
Please apply the cleanups I made here, if possible.

**Pull request closed without merging**
