### PR TITLE
Add readthedocs links to README

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Comment by tomdele** [comment]
I have added the link to the GH directly on the main page. 
Don t know if you want to keep it in the README.

**Comment by asanin-epfl** [comment]
> I have added the link to the GH directly on the main page.
Don t know if you want to keep it in the README.

Let @jdcourcol to decide

**Comment by tomdele** [comment]
@jdcourcol  look at :

**Comment by jdcourcol** [comment]
put it in both places. I see pandas and numpy doing the same.

**Review by tomdele — APPROVED** [review]
Looks good

**Comment by asanin-epfl** [comment]
thank you!

**Pull request merged**
