### PR TITLE
The SWC format string used in `sscanf` is unnecessarily clamping the …

### LINKED ISSUE #419: issue with swc morphology
This morphology is not loadable in morphio: [fail.swc.zip](https://github.com/BlueBrain/MorphIO/files/9044455/fail.swc.zip)
with error:
```
MissingParentError: 
test_2.swc:1770:error
Sample id: 1770 refers to non-existant parent ID: 0
```
while when the last line is removed from the file, it can be loaded, and result in a single axon morphology. 

@lidakanari @eleftherioszisis , would you have any idea what is going on? It is a morphology for @YannRoussel

### PR DESCRIPTION
**Pull request by mgeplf**
…size of allowed inputs

* fixes #419

### CODE REVIEW

**Review by eleftherioszisis — APPROVED** [review]

**Comment by arnaudon** [comment]
@eleftherioszisis @mgeplf  would it be possible to release morphio to get this fix on pypi? thanks!

**Comment by mgeplf** [comment]
yup, likely - I'll try and find time to do it shortly

**Comment by arnaudon** [comment]
Thank you very much!

**Comment by arnaudon** [comment]
No rush, I just managed to compile morphio on bb5 for now

**Comment by mgeplf** [comment]
In the future, you can grab the wheels that are built by CI from here:
https://github.com/BlueBrain/MorphIO/actions/runs/2615912478

Saves having to deal with compilation.

**Comment by arnaudon** [comment]
ah nice, it's fine, I just had to module load cmake/gcc to make it work

**Pull request merged**
