### PR TITLE
Warn about zero diameter in SWC morphology

### PR DESCRIPTION
**Pull request by asanin-epfl**
@tomdele should we rather throw an error if diameter is 0? Should we check H5 and ASC as well for this?
Solution to #299

### CODE REVIEW

**Comment by tomdele** [comment]
Hum ... I am not sure if this can be a use case or not. 
@arnaudon any insights ?

**Comment by asanin-epfl** [comment]
It is a usecase when .swc is made by conversion of .asc.

**Comment by tomdele** [comment]
Ok I see. 
Anyway, thinking about it, we should probably warn and not throw. I think if something is not explicitly in the specs, we should not interpret. Even if it does not make sense. As a rule of thumb, we should not create sub-specs, otherwise it will backfire at some point.

**Review by tomdele — APPROVED** [review]
Looks good

**Comment by asanin-epfl** [comment]
Thank you!

> ... it will backfire at some point.

I agree. That's why warning is ok in this case. Also SWC is the only appropriate format because H5 and ASC can have contour somas.

**Comment by tomdele** [comment]
> That's why warning is ok in this case. 

indeed it makes perfect sense here.

**Pull request merged**
