### PR TITLE
Fix bug: h5 files were not sanitized when no modifier was passed

### PR DESCRIPTION
**Pull request by wizmer**
Sanitization now always happens.

### CODE REVIEW

**Comment by asanin-epfl** [comment]
I think you would need a review from someone with more rights to this repo.

**Comment by mgeplf** [comment]
Could you add a test?

I think we need more tests in general of this code, and not just relying on NeuroM to catch things.

**Comment by wizmer** [comment]
I have already added the test ` test_single_children`. I think we are good.

**Comment by mgeplf** [comment]
missed that; shouldn't it check w/ all options?

**Comment by wizmer** [comment]
The test for Neurolucida is here
https://github.com/BlueBrain/MorphIO/blob/master/tests/test_2_neurolucida.py#L304

And for SWC, sanitization does nothing (there are no single child section, no duplicates issues) so I can't check it.

**Comment by matz-e** [comment]
This seems like a major breaking change, but was not treated as such?

**Comment by wizmer** [comment]
It depends who 'breaking' refers to. It's not breaking API-wise but yes it's an important change.

**Pull request merged**
