### PR TITLE
better documentation of MorphIO warnings

### PR DESCRIPTION
**Pull request by asanin-epfl**

### CODE REVIEW

**Review by arnaudon — APPROVED** [review]

**Review by adrien-berchet — APPROVED** [review]

**Comment by asanin-epfl** [comment]
@tomdele I would still need your approval here

**Review by tomdele — APPROVED** [review]
That s awesome

**Comment by tomdele** [comment]
>  @tomdele I would still need your approval here

Thx for the ping I totally missed it  ...

**Comment by asanin-epfl** [comment]
Thank you!

**Pull request merged**
