### PR TITLE
Fix for compat with recent HighFive

### PR DESCRIPTION
**Pull request by ferdonline**
Recent Highfive is a bit picky with raw arrays. Plus, this looks prettier c++

### CODE REVIEW

**Comment by ferdonline** [comment]
CI is failing for some error in the CI itself

**Comment by mgeplf** [comment]
Should be fixed by: https://github.com/BlueBrain/MorphIO/pull/269

**Comment by ferdonline** [comment]
Still not.
Please use the option `--parallel 2`

**Comment by tomdele** [comment]
Did you rebase ?

**Comment by ferdonline** [comment]
Oh, jumped too quickly to conclusions on failing test in Highfive, sorry. It should be fine, will rebase

**Comment by mgeplf** [comment]
LGTM

**Review by mgeplf — APPROVED** [review]

**Pull request merged**
