### PR TITLE
Fix the no soma h5 morphologies

### PR DESCRIPTION
**Pull request by tomdele**
Fix the no soma morphologies. The single-neurite.h5 is : 
```
HDF5 "single-neurite.h5" {
GROUP "/" {
   DATASET "points" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 3, 4 ) / ( 3, 4 ) }
      DATA {
      (0,0): 4, 0, 0, 2,
      (1,0): 5, 0, 0, 2,
      (2,0): 6, 0, 0, 2
      }
   }
   DATASET "structure" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 1, 3 ) / ( 1, 3 ) }
      DATA {
      (0,0): 0, 2, 0
      }
   }
}
}
```

### CODE REVIEW

**Review by asanin-epfl — APPROVED** [review]

**Comment by asanin-epfl** [comment]
Could be useful to check for soma types in the new added tests, but it's up to you

**Comment by tomdele** [comment]
Good idea. I will do it. I need to rebase on your test PR anyway.

**Comment by asanin-epfl** [comment]
What test PR? Do I have one?

**Comment by tomdele** [comment]
I meant your pytest PR

**Comment by tomdele** [comment]
Rah not PR (we merged it already) commit.

**Pull request merged**
